#include "CpythonContract.h"
#include "CpythonSpec.h"

#include <cctype>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>

namespace {

void writeString(std::ostream &os, std::string_view text) {
  os << '"';
  for (unsigned char byte : text) {
    switch (byte) {
    case '\\':
      os << "\\\\";
      break;
    case '"':
      os << "\\\"";
      break;
    case '\n':
      os << "\\n";
      break;
    case '\r':
      os << "\\r";
      break;
    case '\t':
      os << "\\t";
      break;
    default:
      if (std::isprint(byte)) {
        os << static_cast<char>(byte);
      } else {
        constexpr char digits[] = "01234567";
        os << '\\' << digits[(byte >> 6) & 7] << digits[(byte >> 3) & 7]
           << digits[byte & 7];
      }
      break;
    }
  }
  os << '"';
}

void writeChar(std::ostream &os, char ch) {
  if (ch == '\0') {
    os << "'\\0'";
    return;
  }
  if (ch == '\\') {
    os << "'\\\\'";
    return;
  }
  if (ch == '\'') {
    os << "'\\''";
    return;
  }
  if (ch == '\n') {
    os << "'\\n'";
    return;
  }
  if (ch == '\r') {
    os << "'\\r'";
    return;
  }
  if (ch == '\t') {
    os << "'\\t'";
    return;
  }
  os << '\'' << ch << '\'';
}

const char *kindName(lython::parser::CpythonPegExprKind kind) {
  using lython::parser::CpythonPegExprKind;
  switch (kind) {
  case CpythonPegExprKind::Empty:
    return "CpythonPegExprKind::Empty";
  case CpythonPegExprKind::Name:
    return "CpythonPegExprKind::Name";
  case CpythonPegExprKind::Literal:
    return "CpythonPegExprKind::Literal";
  case CpythonPegExprKind::Sequence:
    return "CpythonPegExprKind::Sequence";
  case CpythonPegExprKind::Choice:
    return "CpythonPegExprKind::Choice";
  case CpythonPegExprKind::Optional:
    return "CpythonPegExprKind::Optional";
  case CpythonPegExprKind::Repeat0:
    return "CpythonPegExprKind::Repeat0";
  case CpythonPegExprKind::Repeat1:
    return "CpythonPegExprKind::Repeat1";
  case CpythonPegExprKind::SepRepeat1:
    return "CpythonPegExprKind::SepRepeat1";
  case CpythonPegExprKind::And:
    return "CpythonPegExprKind::And";
  case CpythonPegExprKind::Not:
    return "CpythonPegExprKind::Not";
  case CpythonPegExprKind::Eager:
    return "CpythonPegExprKind::Eager";
  case CpythonPegExprKind::Cut:
    return "CpythonPegExprKind::Cut";
  }
  return "CpythonPegExprKind::Empty";
}

template <typename Range, typename Writer>
void writeList(std::ostream &os, const Range &range, Writer writer) {
  os << "{";
  bool first = true;
  for (const auto &item : range) {
    if (!first)
      os << ", ";
    first = false;
    writer(os, item);
  }
  os << "}";
}

void writeStringList(std::ostream &os, const std::vector<std::string> &values) {
  writeList(os, values, [](std::ostream &out, const std::string &value) {
    writeString(out, value);
  });
}

void writeExpr(std::ostream &os, const lython::parser::CpythonPegExpr &expr);

void writeFirstSet(std::ostream &os,
                   const lython::parser::CpythonPegFirstSet &first) {
  os << "CpythonPegFirstSet{" << (first.nullable ? "true" : "false") << ", "
     << (first.unknown ? "true" : "false") << ", ";
  writeStringList(os, first.literals);
  os << ", ";
  writeStringList(os, first.tokens);
  os << "}";
}

void writeExpr(std::ostream &os, const lython::parser::CpythonPegExpr &expr) {
  os << "CpythonPegExpr{" << kindName(expr.kind) << ", ";
  writeString(os, expr.value);
  os << ", ";
  writeChar(os, expr.quote);
  os << ", ";
  writeString(os, expr.label);
  os << ", ";
  writeList(os, expr.children,
            [](std::ostream &out, const lython::parser::CpythonPegExpr &child) {
              writeExpr(out, child);
            });
  os << "}";
}

void writeAlternative(std::ostream &os,
                      const lython::parser::CpythonPegAlternative &alt) {
  os << "CpythonPegAlternative{";
  writeExpr(os, alt.expr);
  os << ", ";
  writeString(os, alt.headRule);
  os << ", ";
  writeString(os, alt.action);
  os << ", ";
  writeStringList(os, alt.actionCallees);
  os << ", ";
  writeStringList(os, alt.astConstructors);
  os << ", ";
  writeFirstSet(os, alt.first);
  os << ", ";
  writeFirstSet(os, alt.recoveryFirst);
  os << ", ";
  writeStringList(os, alt.ruleRefs);
  os << ", ";
  writeStringList(os, alt.tokenRefs);
  os << ", ";
  writeStringList(os, alt.literalRefs);
  os << "}";
}

void writeSpec(std::ostream &os, const lython::parser::CpythonSpec &spec) {
  os << "// Generated by CpythonSpecGen. Do not edit.\n";
  os << "CpythonSpec loadGeneratedSpec() {\n";
  os << "  CpythonSpec spec;\n";

  os << "  spec.tokens = ";
  writeList(os, spec.tokens,
            [](std::ostream &out, const lython::parser::TokenSpec &token) {
              out << "TokenSpec{" << token.id << ", ";
              writeString(out, token.name);
              out << ", ";
              writeString(out, token.spelling);
              out << "}";
            });
  os << ";\n";

  auto writeNamedStringList = [&](const char *name,
                                  const std::vector<std::string> &values) {
    os << "  spec." << name << " = ";
    writeStringList(os, values);
    os << ";\n";
  };

  writeNamedStringList("tokenNames", spec.tokenNames);
  writeNamedStringList("hardKeywords", spec.hardKeywords);
  writeNamedStringList("softKeywords", spec.softKeywords);
  writeNamedStringList("grammarHardKeywords", spec.grammarHardKeywords);
  writeNamedStringList("grammarSoftKeywords", spec.grammarSoftKeywords);
  writeNamedStringList("generatedHardKeywords", spec.generatedHardKeywords);
  writeNamedStringList("generatedSoftKeywords", spec.generatedSoftKeywords);
  writeNamedStringList("operatorSpellings", spec.operatorSpellings);
  writeNamedStringList("astNodeKinds", spec.astNodeKinds);

  os << "  spec.generatedHardKeywordSpecs = ";
  writeList(os, spec.generatedHardKeywordSpecs,
            [](std::ostream &out,
               const lython::parser::GeneratedKeywordSpec &keyword) {
              out << "GeneratedKeywordSpec{";
              writeString(out, keyword.text);
              out << ", " << keyword.tokenId << "}";
            });
  os << ";\n";

  os << "  spec.generatedTokenRefs = ";
  writeList(os, spec.generatedTokenRefs,
            [](std::ostream &out,
               const lython::parser::GeneratedTokenRefSpec &token) {
              out << "GeneratedTokenRefSpec{";
              writeString(out, token.text);
              out << ", " << token.tokenId << "}";
            });
  os << ";\n";

  os << "  spec.generatedHardKeywordTokenIdByText = ";
  writeList(os, spec.generatedHardKeywordTokenIdByText,
            [](std::ostream &out, const auto &entry) {
              out << "{";
              writeString(out, entry.first);
              out << ", " << entry.second << "}";
            });
  os << ";\n";

  os << "  spec.tokenNameBySpelling = ";
  writeList(os, spec.tokenNameBySpelling,
            [](std::ostream &out, const auto &entry) {
              out << "{";
              writeString(out, entry.first);
              out << ", ";
              writeString(out, entry.second);
              out << "}";
            });
  os << ";\n";

  auto writeStringIntMap = [&](const char *name,
                               const std::map<std::string, int> &values) {
    os << "  spec." << name << " = ";
    writeList(os, values, [](std::ostream &out, const auto &entry) {
      out << "{";
      writeString(out, entry.first);
      out << ", " << entry.second << "}";
    });
    os << ";\n";
  };
  writeStringIntMap("tokenIdByName", spec.tokenIdByName);
  writeStringIntMap("tokenIdBySpelling", spec.tokenIdBySpelling);
  writeStringIntMap("generatedRuleTypeIds", spec.generatedRuleTypeIds);

  os << "  spec.astKindTypes = ";
  writeList(os, spec.astKindTypes, [](std::ostream &out, const auto &entry) {
    out << "{";
    writeString(out, entry.first);
    out << ", ";
    writeString(out, entry.second);
    out << "}";
  });
  os << ";\n";

  os << "  spec.astFields = ";
  writeList(os, spec.astFields, [](std::ostream &out, const auto &entry) {
    out << "{";
    writeString(out, entry.first);
    out << ", ";
    writeStringList(out, entry.second);
    out << "}";
  });
  os << ";\n";

  os << "  spec.astFieldSpecs = ";
  writeList(os, spec.astFieldSpecs, [](std::ostream &out, const auto &entry) {
    out << "{";
    writeString(out, entry.first);
    out << ", ";
    writeList(
        out, entry.second,
        [](std::ostream &nested, const lython::parser::AstFieldSpec &field) {
          nested << "AstFieldSpec{";
          writeString(nested, field.name);
          nested << ", ";
          writeString(nested, field.type);
          nested << ", " << (field.optional ? "true" : "false") << ", "
                 << (field.sequence ? "true" : "false") << ", "
                 << (field.nullableElement ? "true" : "false") << "}";
        });
    out << "}";
  });
  os << ";\n";

  os << "  spec.generatedRules = ";
  writeList(
      os, spec.generatedRules,
      [](std::ostream &out, const lython::parser::GeneratedRuleSpec &rule) {
        out << "GeneratedRuleSpec{";
        writeString(out, rule.name);
        out << ", ";
        writeString(out, rule.functionName);
        out << ", ";
        writeString(out, rule.returnType);
        out << ", " << rule.typeId << "}";
      });
  os << ";\n";

  os << "  spec.generatedRuleIndices = ";
  writeList(os, spec.generatedRuleIndices,
            [](std::ostream &out, const auto &entry) {
              out << "{";
              writeString(out, entry.first);
              out << ", static_cast<std::size_t>(" << entry.second << ")}";
            });
  os << ";\n";

  os << "  spec.peg.rules = ";
  writeList(os, spec.peg.rules,
            [](std::ostream &out, const lython::parser::CpythonPegRule &rule) {
              out << "CpythonPegRule{";
              writeString(out, rule.name);
              out << ", ";
              writeString(out, rule.returnType);
              out << ", " << (rule.memo ? "true" : "false") << ", "
                  << (rule.invalid ? "true" : "false") << ", ";
              writeExpr(out, rule.expr);
              out << ", ";
              writeFirstSet(out, rule.first);
              out << ", ";
              writeFirstSet(out, rule.recoveryFirst);
              out << ", ";
              writeList(
                  out, rule.alternatives,
                  [](std::ostream &nested,
                     const lython::parser::CpythonPegAlternative &alternative) {
                    writeAlternative(nested, alternative);
                  });
              out << "}";
            });
  os << ";\n";

  os << "  spec.peg.ruleIndices = ";
  writeList(os, spec.peg.ruleIndices, [](std::ostream &out, const auto &entry) {
    out << "{";
    writeString(out, entry.first);
    out << ", static_cast<std::size_t>(" << entry.second << ")}";
  });
  os << ";\n";

  os << "  spec.peg.diagnostics = ";
  writeStringList(os, spec.peg.diagnostics);
  os << ";\n";

  os << "  return spec;\n";
  os << "}\n";
}

} // namespace

int main(int argc, char **argv) {
  if (argc != 2) {
    std::cerr << "usage: CpythonSpecGen <output.inc>\n";
    return 1;
  }

  std::ofstream output(argv[1]);
  if (!output) {
    std::cerr << "failed to open output file: " << argv[1] << "\n";
    return 1;
  }

  lython::parser::Diagnostics diagnostics;
  lython::parser::validateCpythonParserContract(diagnostics);
  if (!diagnostics.empty()) {
    std::cerr << "vendored CPython parser contract validation failed:\n";
    for (const lython::parser::Diagnostic &diagnostic : diagnostics)
      std::cerr << "- " << diagnostic.message << "\n";
    return 1;
  }

  writeSpec(output, lython::parser::cpython314Spec());
  return output ? 0 : 1;
}
