eg = ExceptionGroup("boom", [ValueError("a"), TypeError("b")])
print(eg)
print(repr(eg))
print(eg.message)
excs = eg.exceptions
print(len(excs))
print(repr(excs[0]))
print(repr(excs[1]))
single = BaseExceptionGroup("one", [KeyError("k")])
print(single)
print(repr(single))
inner = ExceptionGroup("inner", [ValueError("v"), KeyError("k")])
outer = ExceptionGroup("outer", [inner, TypeError("t")])
print(outer)
print(repr(outer))
print(len(outer.exceptions))
