# int の format spec mini-language を CPython 3.14 の実出力でピン留めする。
# fill/align/sign/#/0/width/grouping/type (b/c/d/n/o/x/X) と負数・bigint。
x = 1234
print(f"{x}")
print(f"{x:d}")
print(f"{x:b}")
print(f"{x:o}")
print(f"{x:x}")
print(f"{x:X}")
print(f"{x:n}")
print(f"{x:#b}")
print(f"{x:#o}")
print(f"{x:#x}")
print(f"{x:#X}")
print(f"{x:+d}")
print(f"{x: d}")
print(f"{x:-d}")
print(f"{x:08d}")
print(f"{x:8d}")
print(f"{x:<8d}|")
print(f"{x:>8d}")
print(f"{x:^8d}|")
print(f"{x:=8d}")
print(f"{x:,d}")
print(f"{x:_d}")
print(f"{x:_b}")
print(f"{x:_x}")
print(f"{x:,}")
print(f"{x:#010x}")
print(f"{x:+#012_b}")
print(f"{x:08,d}")
print(f"{x:0=+9,d}")
print(f"{x:*<6d}|")
print(f"{x:09_d}")
n = -1234
print(f"{n:08,d}")
print(f"{n:0=+9,d}")
print(f"{n:#x}")
print(f"{n:=8d}")
zero = 0
print(f"{zero:08,d}")
print(f"{zero:#o}")
print(f"{zero:=5d}")
big = 10 ** 25
print(f"{big:,d}")
print(f"{big:_x}")
print(f"{-big:,d}")
# 'c' は code point
print(f"{65:c}")
print(f"{955:c}")
print(f"{1234:5c}|")
print(f"{1234:05c}")
# int を float 系 type で
print(f"{x:e}")
print(f"{x:.2f}")
print(f"{x:g}")
print(f"{zero:%}")
# bool は空 spec で str、非空 spec で int 経路
print(f"{True}")
print(f"{True:d}")
print(f"{True:05}")
print(f"{False:>5}")
print(f"{True:.1f}")
