# open() with a str-literal 'b' mode statically selects the binary arm and
# returns the Buffered* wrapper CPython does, over the raw FileIO.
f = open("open_binary_case.tmp", "wb")
print(f.write(b"binary\x00mode"))
f.close()
g = open("open_binary_case.tmp", "rb")
print(g.read())
print(g.seek(0))
print(g.read(6))
print(g.readable())
print(g.writable())
g.close()
t = open("open_binary_case.tmp")
print(t.readable())
t.close()
