# os.path's pure-string surface: every answer here is CPython 3.14's,
# byte for byte. Reached through both spellings -- `os.path.X` (which is
# os.py's `import posixpath as path`) and `posixpath.X` directly.
import os
import posixpath

# --- os.path: pure string surface (identical answers in CPython) ------------
print(os.path.join("a", "b"))
print(os.path.join("a/", "b"))
print(os.path.join("a", "/b"))
print(os.path.join("", "b"))
print(os.path.join("a", ""))
print(os.path.join("a", "b", "c", "d"))
print(os.path.split("/x/y"))
print(os.path.split("/x/"))
print(os.path.split("x"))
print(os.path.split("/"))
print(os.path.splitext("/x/y.txt"))
print(os.path.splitext("/x/.cshrc"))
print(os.path.splitext("/x/y"))
print(os.path.splitext("x.tar.gz"))
print(os.path.splitext(".."))
print(os.path.basename("/x/y.txt"))
print(os.path.basename("/x/"))
print(os.path.dirname("/x/y.txt"))
print(os.path.dirname("x"))
print(os.path.dirname("/"))
print(os.path.isabs("/x"))
print(os.path.isabs("x"))
print(os.path.normcase("A/b"))
print(os.path.normpath("a/./b/../c"))
print(os.path.normpath("a//b"))
print(os.path.normpath("/a/../.."))
print(os.path.normpath("../a"))
print(os.path.normpath("a/../../b"))
print(os.path.normpath("a/../../../b"))
print(os.path.normpath(""))
print(os.path.normpath("."))
print(os.path.normpath("//a//b"))
print(os.path.normpath("///a"))
print(os.path.normpath("/"))
print(os.path.normpath("a/.."))
print(os.path.normpath("../.."))
print(posixpath.normpath("x/./"))
print(os.sep, os.curdir, os.pardir, os.extsep, os.pathsep, os.linesep == "\n")
print(os.name)
print(posixpath.sep, posixpath.curdir)
