print("straße".upper())
print("STRASSE".lower())
print("İstanbul".lower())
print("ΟΔΟΣ".lower())
print("ὈΔΥΣΣΕΎΣ ΟΔΟΣ".lower())
print("Straße".casefold())
print("ΣΊΣΥΦΟΣ".casefold())
print("hello world".title())
print("they're bill's friends".title())
print("ǆungla ǳin".title())
print("ß first".capitalize())
print("hELLO".capitalize())
print("Hello World".swapcase())
print("ΟΔΟΣ abc".swapcase())
print("ᾳ".title())
print("Hello World".istitle())
print("Hello world".istitle())
print("ǅungla".istitle())
print("abc123".isalnum())
print("Ⅳ".isalnum())
print("abc!".isalnum())
print("my_var1".isidentifier())
print("1var".isidentifier())
print("_".isidentifier())
print("λ".isidentifier())
print("".isidentifier())
print("abc".isascii())
print("straße".isascii())
print("".isascii())
print("½".isnumeric())
print("½".isdigit())
print("½".isdecimal())
print("²".isdigit())
print("²".isdecimal())
print("Dž".isupper())
print("Dž".islower())
print("DŽ".isupper())
print("\t\n ".isspace())
print("San Serriffe".isalpha())
print("SanSerriffe".isalpha())
print("hello\n".isprintable())
print("hello".isprintable())
