s = "the quick brown fox jumps over the lazy dog"
print(s.find("the"))
print(s.find("the", 1))
print(s.find("cat"))
print(s.rfind("the"))
print(s.index("quick"))
print(s.rindex("o"))
print(s.count("o"))
print(s.count("the"))
print(s.count(""))
print(s.startswith("the q"))
print(s.startswith("quick", 4))
print(s.startswith("quick", 4, 8))
print(s.endswith("dog"))
print(s.endswith("lazy", 0, 39))
print("あいうえお".find("うえ"))
print("あいうえお".count("あ"))
print("  padded  ".strip() + "|")
print("  padded  ".lstrip() + "|")
print("  padded  ".rstrip() + "|")
print("xxyzhelloxzy".strip("xyz"))
print("www.example.com".lstrip("cmowz."))
print("TestCase".removeprefix("Test"))
print("TestCase".removeprefix("Case"))
print("TestCase".removesuffix("Case"))
print("one one one".replace("one", "two"))
print("one one one".replace("one", "two", 2))
print("abc".replace("", "*"))
print("コンコン".replace("コ", "ゴン"))
print("[" + "mid".center(9) + "]")
print("mid".center(9, "*"))
print("mid".center(8, "*"))
print("7".rjust(4, "0"))
print("7".ljust(4, "_"))
print("-99".zfill(6))
print("+3".zfill(5))
print("wide".zfill(2))
print("a\tbb\tccc".expandtabs(4))
print("a\tbb\tccc".expandtabs())
print("na" * 4 + " batman")
print("あ" * 3)
print("x" * 0 + "|")
try:
    s.index("missing")
except ValueError as e:
    print("index:", e)
try:
    "abc".rindex("z")
except ValueError as e:
    print("rindex:", e)
