from __future__ import annotations

from typing import Generic, List, Type, TypeVar, TypeVarTuple, Unpack

__all__ = [
    "Prim",
    "i1",
    "i8",
    "i16",
    "i32",
    "i64",
    "i128",
    "i256",
    "f16",
    "f32",
    "f64",
    "f128",
    "f256",
    "Vector",
    "Matrix",
    "Tensor",
]

PrimT = TypeVar("PrimT", bound=Prim)

class Prim(Generic[PrimT]):
    """Base class for all primitive types"""

    def __add__(self: PrimT, other: PrimT) -> PrimT: ...
    def __sub__(self: PrimT, other: PrimT) -> PrimT: ...
    def __mul__(self: PrimT, other: PrimT) -> PrimT: ...
    def __neg__(self: PrimT) -> PrimT: ...
    def __lt__(self: PrimT, other: PrimT) -> i1: ...
    def __le__(self: PrimT, other: PrimT) -> i1: ...
    def __eq__(self: PrimT, other: PrimT) -> i1: ...
    def __ne__(self: PrimT, other: PrimT) -> i1: ...
    def __gt__(self: PrimT, other: PrimT) -> i1: ...
    def __ge__(self: PrimT, other: PrimT) -> i1: ...

IntT = TypeVar("IntT", bound=PrimInt)
FloatT = TypeVar("FloatT", bound=PrimFloat)

class PrimInt(Generic[IntT], Prim[IntT]):
    """Intermediate class for integer primitives"""

    def __div__(self: IntT, other: IntT) -> PrimFloat[PrimFloat]: ...
    def __mod__(self: IntT, other: IntT) -> PrimInt[IntT]: ...

class PrimFloat(Generic[FloatT], Prim[FloatT]):
    """Intermediate class for floating-point primitives"""

    def __truediv__(self: FloatT, other: FloatT) -> PrimFloat[FloatT]: ...
    def __floordiv__(self: FloatT, other: FloatT) -> PrimFloat[FloatT]: ...

class i1(PrimInt[i1]): ...
class i8(PrimInt[i8]): ...
class i16(PrimInt[i16]): ...
class i32(PrimInt[i32]): ...
class i64(PrimInt[i64]): ...
class i128(PrimInt[i128]): ...
class i256(PrimInt[i256]): ...
class f16(PrimFloat[f16]): ...
class f32(PrimFloat[f32]): ...
class f64(PrimFloat[f64]): ...
class f128(PrimFloat[f128]): ...
class f256(PrimFloat[f256]): ...

type NumberLike = Prim | int | float

Shape = TypeVarTuple("Shape")

class Vector:
    def __class_getitem__(cls, key: tuple[Prim, int]) -> Type[Vector]: ...

    def __init__(self, value: List[NumberLike]) -> None: ...

    @classmethod
    def zeros(cls) -> Vector: ...
    @classmethod
    def ones(cls) -> Vector: ...
    @classmethod
    def full(cls, value: NumberLike) -> Vector: ...

class Matrix:
    def __class_getitem__(cls, key: tuple[Prim, int, int]) -> Type[Matrix]: ...

    def __init__(self, value: List[List[NumberLike]]) -> None: ...

    @classmethod
    def zeros(cls) -> Matrix: ...
    @classmethod
    def ones(cls) -> Matrix: ...
    @classmethod
    def full(cls, value: NumberLike) -> Matrix: ...

class Tensor:
    def __class_getitem__(cls, key: tuple[Prim, Unpack[Shape]]) -> Type[Tensor]: ...

    type _NestedNumberLike = NumberLike | List[_NestedNumberLike]
    def __init__(self, value: _NestedNumberLike) -> None: ...

    @classmethod
    def zeros(cls) -> Tensor: ...
    @classmethod
    def ones(cls) -> Tensor: ...
    @classmethod
    def full(cls, value: NumberLike) -> Tensor: ...
