from __future__ import annotations

from typing import List, TypeVarTuple, Unpack, overload

__all__ = [
    "Prim",
    "Int",
    "Float",
    "Vector",
    "Matrix",
    "Tensor",
]

class Int:
    """Integer primitive type.

    Width is a value-level parameter (`Int[32]` returns `type[Int]`), so every
    width shares this one static type; width mismatches are diagnosed by the
    compiler, not the type checker.
    """

    def __class_getitem__(cls, key: int) -> type[Int]: ...
    def __init__(self, value: int) -> None: ...
    def __add__(self, other: Int) -> Int: ...
    def __sub__(self, other: Int) -> Int: ...
    def __mul__(self, other: Int) -> Int: ...
    def __mod__(self, other: Int) -> Int: ...
    def __neg__(self) -> Int: ...
    def __lt__(self, other: Int) -> Int[1]: ...
    def __le__(self, other: Int) -> Int[1]: ...
    def __eq__(self, other: Int) -> Int[1]: ...  # type: ignore
    def __ne__(self, other: Int) -> Int[1]: ...  # type: ignore
    def __gt__(self, other: Int) -> Int[1]: ...
    def __ge__(self, other: Int) -> Int[1]: ...

class Float:
    """Floating-point primitive type.

    Width is a value-level parameter (`Float[32]` returns `type[Float]`), so
    every width shares this one static type; width mismatches are diagnosed by
    the compiler, not the type checker.
    """

    def __class_getitem__(cls, key: int) -> type[Float]: ...
    def __init__(self, value: int | float) -> None: ...
    def __add__(self, other: Float) -> Float: ...
    def __sub__(self, other: Float) -> Float: ...
    def __mul__(self, other: Float) -> Float: ...
    def __truediv__(self, other: Float) -> Float: ...
    def __floordiv__(self, other: Float) -> Float: ...
    def __neg__(self) -> Float: ...
    def __lt__(self, other: Float) -> Int[1]: ...
    def __le__(self, other: Float) -> Int[1]: ...
    def __eq__(self, other: Float) -> Int[1]: ...  # type: ignore
    def __ne__(self, other: Float) -> Int[1]: ...  # type: ignore
    def __gt__(self, other: Float) -> Int[1]: ...
    def __ge__(self, other: Float) -> Int[1]: ...

# Any primitive scalar. A plain union (rather than a generic base class) keeps
# shaped __getitem__ results assignable everywhere a scalar is accepted --
# a generic Prim[T] base is invariant in T, which made Prim[Int | Float],
# Prim[Int] and Prim[Float] mutually incompatible.
type Prim = Int | Float

type NumberLike = Prim | int | float

# 添字はリテラルなら静的に範囲検査され、ランタイム整数 (Python int / Int)
# なら静的 shape を境界として実行時に検査される (範囲外は trap)。
type IndexLike = int | Int

Shape = TypeVarTuple("Shape")

class Vector:
    def __class_getitem__(cls, key: tuple[type[Prim], int]) -> type[Vector]: ...
    def __init__(self, value: List[NumberLike]) -> None: ...
    # スカラー (NumberLike) は shape へ splat されて elementwise に broadcast
    # される。整数要素へは整数スカラーのみ (dtype は暗黙に変わらない)。
    def __add__(self, other: Vector | NumberLike) -> Vector: ...
    def __sub__(self, other: Vector | NumberLike) -> Vector: ...
    def __mul__(self, other: Vector | NumberLike) -> Vector: ...
    def __truediv__(self, other: Vector | NumberLike) -> Vector: ...
    def __radd__(self, other: NumberLike) -> Vector: ...
    def __rsub__(self, other: NumberLike) -> Vector: ...
    def __rmul__(self, other: NumberLike) -> Vector: ...
    def __rtruediv__(self, other: NumberLike) -> Vector: ...
    # @ はオペランドの rank で契約を選ぶ: Vector @ Vector は dot (スカラー)、
    # Vector @ Matrix は vecmat
    @overload
    def __matmul__(self, other: Vector) -> Prim: ...
    @overload
    def __matmul__(self, other: Matrix) -> Vector: ...
    # Element assignment differs from a Python container's: shaped primitives
    # are values, so `b = a; b[0] = x` rebinds `b` alone and leaves `a` at its
    # old contents. The target must be a named local for that rebinding to be
    # observable at all.
    def __getitem__(self, key: IndexLike) -> Prim: ...
    def __setitem__(self, key: IndexLike, value: NumberLike) -> None: ...
    @classmethod
    def zeros(cls) -> Vector: ...
    @classmethod
    def ones(cls) -> Vector: ...
    @classmethod
    def full(cls, value: NumberLike) -> Vector: ...

class Matrix:
    def __class_getitem__(
        cls, key: tuple[type[Prim], int, int]
    ) -> type[Matrix]: ...
    def __init__(self, value: List[List[NumberLike]]) -> None: ...
    def __add__(self, other: Matrix | NumberLike) -> Matrix: ...
    def __sub__(self, other: Matrix | NumberLike) -> Matrix: ...
    def __mul__(self, other: Matrix | NumberLike) -> Matrix: ...
    def __truediv__(self, other: Matrix | NumberLike) -> Matrix: ...
    def __radd__(self, other: NumberLike) -> Matrix: ...
    def __rsub__(self, other: NumberLike) -> Matrix: ...
    def __rmul__(self, other: NumberLike) -> Matrix: ...
    def __rtruediv__(self, other: NumberLike) -> Matrix: ...
    @overload
    def __matmul__(self, other: Matrix) -> Matrix: ...
    @overload
    def __matmul__(self, other: Vector) -> Vector: ...
    def __getitem__(self, key: tuple[IndexLike, IndexLike]) -> Prim: ...
    def __setitem__(
        self, key: tuple[IndexLike, IndexLike], value: NumberLike
    ) -> None: ...
    @classmethod
    def zeros(cls) -> Matrix: ...
    @classmethod
    def ones(cls) -> Matrix: ...
    @classmethod
    def full(cls, value: NumberLike) -> Matrix: ...

class Tensor:
    def __class_getitem__(
        cls, key: tuple[type[Prim], Unpack[Shape]]
    ) -> type[Tensor]: ...

    type _NestedNumberLike = NumberLike | List[_NestedNumberLike]
    def __init__(self, value: _NestedNumberLike) -> None: ...
    def __add__(self, other: Tensor | NumberLike) -> Tensor: ...
    def __sub__(self, other: Tensor | NumberLike) -> Tensor: ...
    def __mul__(self, other: Tensor | NumberLike) -> Tensor: ...
    def __truediv__(self, other: Tensor | NumberLike) -> Tensor: ...
    def __radd__(self, other: NumberLike) -> Tensor: ...
    def __rsub__(self, other: NumberLike) -> Tensor: ...
    def __rmul__(self, other: NumberLike) -> Tensor: ...
    def __rtruediv__(self, other: NumberLike) -> Tensor: ...
    # 等 rank (>=3) 同士のバッチ行列積: 先頭次元は一致が必要 (batch broadcast
    # なし)、末尾 2 次元で契約する。rank-2 同士は行列積
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __getitem__(self, key: tuple[IndexLike, ...]) -> Prim: ...
    def __setitem__(
        self, key: tuple[IndexLike, ...], value: NumberLike
    ) -> None: ...
    @classmethod
    def zeros(cls) -> Tensor: ...
    @classmethod
    def ones(cls) -> Tensor: ...
    @classmethod
    def full(cls, value: NumberLike) -> Tensor: ...
