from __future__ import annotations

__all__ = [
    "prim",
    "i1",
    "i8",
    "i16",
    "i32",
    "i64",
    "i128",
    "i256",
    "f16",
    "f32",
    "f64",
    "f128",
    "f256",
]

class prim:
    def __add__(self, other: i8) -> i8: ...
    def __sub__(self, other: i8) -> i8: ...
    def __mul__(self, other: i8) -> i8: ...
    def __lt__(self, other: i8) -> i1: ...
    def __le__(self, other: i8) -> i1: ...
    def __eq__(self, other: i8) -> i1:  # type: ignore
        ...

    def __ne__(self, other: i8) -> i1:  # type: ignore
        ...

    def __gt__(self, other: i8) -> i1: ...
    def __ge__(self, other: i8) -> i1: ...

class i1(prim): ...
class i8(prim): ...
class i16(prim): ...
class i32(prim): ...
class i64(prim): ...
class i128(prim): ...
class i256(prim): ...
class f16(prim): ...
class f32(prim): ...
class f64(prim): ...
class f128(prim): ...
class f256(prim): ...
