from __future__ import annotations

__all__ = ["prim", "i1", "i8"]

class prim: ...

class i1(prim):
    def __eq__(self, other: i1) -> i1:  # type: ignore
        ...

    def __ne__(self, other: i1) -> i1:  # type: ignore
        ...

class i8(prim):
    def __add__(self, other: i8) -> i8: ...
    def __sub__(self, other: i8) -> i8: ...
    def __mul__(self, other: i8) -> i8: ...
    def __lt__(self, other: i8) -> i1: ...
    def __le__(self, other: i8) -> i1: ...
    def __eq__(self, other: i8) -> i1:  # type: ignore
        ...

    def __ne__(self, other: i8) -> i1:  # type: ignore
        ...

    def __gt__(self, other: i8) -> i1: ...
    def __ge__(self, other: i8) -> i1: ...
