// Validates the checked-in Unicode 16.0.0 tables (generated by
// tools/gen_unicode_tables.py) through the same two-stage lookup and
// extended-case decoding the runtime accessors in _ucd.mlir perform. The
// MLIR side is a mechanical mirror of this arithmetic, so pinning the data
// here pins the runtime's case mappings, categories and numeric properties
// without needing a JIT.

#include "UnicodeTablesData.inc"

#include <gtest/gtest.h>

#include <cstdint>
#include <string>
#include <vector>

namespace {

using namespace lython_ucd;

struct CType {
  std::int64_t upper;
  std::int64_t lower;
  std::int64_t fold;
  std::int64_t decimal;
  std::int64_t digit;
  std::int64_t flags;
};

int twoStage(const std::uint16_t *index1, const std::uint16_t *index2,
             char32_t cp) {
  const std::uint16_t block = index1[cp >> kShift];
  return index2[(static_cast<std::size_t>(block) << kShift) +
                (cp & ((1 << kShift) - 1))];
}

CType ctypeOf(char32_t cp) {
  const int record = cp < 0x110000
                         ? twoStage(kCTypeIndex1, kCTypeIndex2, cp)
                         : kDefaultCType;
  const std::int32_t *fields = &kCTypeRecords[record * 6];
  return CType{fields[0], fields[1], fields[2], fields[3], fields[4],
               fields[5]};
}

std::string categoryOf(char32_t cp) {
  const int record = cp < 0x110000 ? twoStage(kInfoIndex1, kInfoIndex2, cp)
                                   : kDefaultInfo;
  return kCategoryNames[kInfoRecords[record * 2]];
}

double numericOf(char32_t cp, bool *has) {
  const int record = cp < 0x110000 ? twoStage(kInfoIndex1, kInfoIndex2, cp)
                                   : kDefaultInfo;
  const std::int32_t index = kInfoRecords[record * 2 + 1];
  *has = index >= 0;
  return *has ? kNumericValues[index] : 0.0;
}

std::vector<char32_t> expand(char32_t cp, std::int64_t value, bool extended) {
  if (!extended)
    return {static_cast<char32_t>(cp + value)};
  const std::int64_t offset = value >> 8;
  const std::int64_t length = value & 0xFF;
  std::vector<char32_t> result;
  for (std::int64_t i = 0; i < length; ++i)
    result.push_back(static_cast<char32_t>(kExtCase[offset + i]));
  return result;
}

std::vector<char32_t> fullUpper(char32_t cp) {
  const CType record = ctypeOf(cp);
  return expand(cp, record.upper, record.flags & kFlagExtUpper);
}

std::vector<char32_t> fullLower(char32_t cp) {
  const CType record = ctypeOf(cp);
  return expand(cp, record.lower, record.flags & kFlagExtLower);
}

std::vector<char32_t> fullFold(char32_t cp) {
  const CType record = ctypeOf(cp);
  return expand(cp, record.fold, record.flags & kFlagExtFold);
}

using U32 = std::vector<char32_t>;

TEST(UnicodeTablesTest, FullSpecialCasingUppercasesSharpS) {
  // "ß".upper() == "SS" -- the canonical full-casing example from R4.
  EXPECT_EQ(fullUpper(U'ß'), (U32{U'S', U'S'}));
}

TEST(UnicodeTablesTest, SimpleCaseDeltasRoundTripAscii) {
  EXPECT_EQ(fullUpper(U'a'), (U32{U'A'}));
  EXPECT_EQ(fullLower(U'A'), (U32{U'a'}));
  EXPECT_EQ(fullUpper(U'A'), (U32{U'A'}));
}

TEST(UnicodeTablesTest, DottedCapitalILowersToTwoCodePoints) {
  // U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE -> "i" + COMBINING DOT.
  EXPECT_EQ(fullLower(0x0130), (U32{0x0069, 0x0307}));
}

TEST(UnicodeTablesTest, CaseFoldingIsFull) {
  EXPECT_EQ(fullFold(U'ß'), (U32{U's', U's'}));
  EXPECT_EQ(fullFold(0x03A3), (U32{0x03C3}));  // Σ -> σ (no context rule)
  EXPECT_EQ(fullFold(U'A'), (U32{U'a'}));
  // U+FB03 LATIN SMALL LIGATURE FFI folds to "ffi".
  EXPECT_EQ(fullFold(0xFB03), (U32{U'f', U'f', U'i'}));
}

TEST(UnicodeTablesTest, CategoriesMatchCPython) {
  EXPECT_EQ(categoryOf(U'A'), "Lu");
  EXPECT_EQ(categoryOf(U'a'), "Ll");
  EXPECT_EQ(categoryOf(0x3042), "Lo");  // HIRAGANA LETTER A
  EXPECT_EQ(categoryOf(0x6F22), "Lo");  // CJK ideograph (in a First..Last range)
  EXPECT_EQ(categoryOf(U'1'), "Nd");
  EXPECT_EQ(categoryOf(U' '), "Zs");
  EXPECT_EQ(categoryOf(U'\n'), "Cc");
  EXPECT_EQ(categoryOf(0x1F600), "So");  // emoji
  EXPECT_EQ(categoryOf(0x0378), "Cn");   // unassigned
  EXPECT_EQ(categoryOf(0x110000), "Cn"); // out of range -> default record
}

TEST(UnicodeTablesTest, NumericPropertiesMatchCPython) {
  bool has = false;
  EXPECT_DOUBLE_EQ(numericOf(0x2163, &has), 4.0);  // Ⅳ ROMAN NUMERAL FOUR
  EXPECT_TRUE(has);
  EXPECT_DOUBLE_EQ(numericOf(0x00BD, &has), 0.5);  // ½
  EXPECT_TRUE(has);
  EXPECT_DOUBLE_EQ(numericOf(0x2153, &has), 1.0 / 3.0);  // ⅓
  EXPECT_TRUE(has);
  EXPECT_DOUBLE_EQ(numericOf(U'7', &has), 7.0);
  EXPECT_TRUE(has);
  numericOf(U'a', &has);
  EXPECT_FALSE(has);
}

TEST(UnicodeTablesTest, DecimalAndDigitFields) {
  EXPECT_EQ(ctypeOf(U'7').decimal, 7);
  EXPECT_EQ(ctypeOf(U'7').digit, 7);
  EXPECT_EQ(ctypeOf(0x00B2).decimal, -1);  // ² has digit but no decimal
  EXPECT_EQ(ctypeOf(0x00B2).digit, 2);
  EXPECT_EQ(ctypeOf(U'a').decimal, -1);
  EXPECT_EQ(ctypeOf(U'a').digit, -1);
}

TEST(UnicodeTablesTest, ClassificationFlags) {
  EXPECT_TRUE(ctypeOf(0x3042).flags & kFlagAlpha);  // ひらがな isalpha
  EXPECT_TRUE(ctypeOf(0x6F22).flags & kFlagAlpha);  // 漢字 isalpha
  EXPECT_FALSE(ctypeOf(U'1').flags & kFlagAlpha);
  EXPECT_TRUE(ctypeOf(0x3000).flags & kFlagSpace);  // IDEOGRAPHIC SPACE
  EXPECT_TRUE(ctypeOf(U'\t').flags & kFlagSpace);   // bidi class S
  EXPECT_TRUE(ctypeOf(U'a').flags & kFlagLower);
  EXPECT_TRUE(ctypeOf(U'A').flags & kFlagUpper);
  EXPECT_TRUE(ctypeOf(0x01C5).flags & kFlagTitle);  // Dž
  EXPECT_TRUE(ctypeOf(U'a').flags & kFlagCased);
  EXPECT_TRUE(ctypeOf(0x0301).flags & kFlagCaseIgnorable);  // combining acute
  // Final_Sigma inputs: Σ itself is cased and not case-ignorable.
  EXPECT_TRUE(ctypeOf(0x03A3).flags & kFlagCased);
  EXPECT_FALSE(ctypeOf(0x03A3).flags & kFlagCaseIgnorable);
}

TEST(UnicodeTablesTest, EveryExtendedReferenceStaysInPool) {
  const std::size_t poolSize = sizeof(kExtCase) / sizeof(kExtCase[0]);
  const std::size_t recordCount =
      sizeof(kCTypeRecords) / sizeof(kCTypeRecords[0]) / 6;
  for (std::size_t record = 0; record < recordCount; ++record) {
    const std::int32_t *fields = &kCTypeRecords[record * 6];
    const std::int32_t flags = fields[5];
    const std::int32_t extFlags[] = {kFlagExtUpper, kFlagExtLower,
                                     kFlagExtFold};
    for (int field = 0; field < 3; ++field) {
      if (!(flags & extFlags[field]))
        continue;
      const std::int32_t packed = fields[field];
      const std::int32_t offset = packed >> 8;
      const std::int32_t length = packed & 0xFF;
      ASSERT_GE(length, 1);
      ASSERT_LE(static_cast<std::size_t>(offset + length), poolSize);
      for (std::int32_t i = 0; i < length; ++i) {
        ASSERT_GE(kExtCase[offset + i], 0);
        ASSERT_LT(kExtCase[offset + i], 0x110000);
      }
    }
  }
}

TEST(UnicodeTablesTest, IndexTablesCoverEveryCodePoint) {
  const std::size_t index2Size = sizeof(kCTypeIndex2) / sizeof(std::uint16_t);
  const std::size_t recordCount =
      sizeof(kCTypeRecords) / sizeof(kCTypeRecords[0]) / 6;
  for (char32_t cp = 0; cp < 0x110000; cp += 97) {  // stride keeps it fast
    const std::uint16_t block = kCTypeIndex1[cp >> kShift];
    const std::size_t row = (static_cast<std::size_t>(block) << kShift) +
                            (cp & ((1 << kShift) - 1));
    ASSERT_LT(row, index2Size);
    ASSERT_LT(kCTypeIndex2[row], recordCount);
  }
}

} // namespace
