name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build wget lsb-release software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo apt-get install -y clang-20 lld-20 llvm-20-dev libmlir-20-dev mlir-20-tools
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.20.0/hyperfine_1.20.0_amd64.deb
          sudo dpkg -i hyperfine_1.20.0_amd64.deb
          uv sync

      - name: Build Lython
        run: |
          cmake -B build -S . -G Ninja \
            -DCMAKE_C_COMPILER=clang-20 \
            -DCMAKE_CXX_COMPILER=clang++-20 \
            -DLLVM_DIR=/usr/lib/llvm-20/lib/cmake/llvm \
            -DMLIR_DIR=/usr/lib/llvm-20/lib/cmake/mlir
          cmake --build build -j$(nproc)

      - name: Test
        run: |
          ./build/bin/lyc jit examples/hello.py
          ./build/bin/lyc jit examples/oop.py
          ./build/bin/lyc jit examples/tarai_prim.py
          ./build/bin/lyc jit examples/tensor_prim.py

      - name: Benchmarks
        run: |
          ./build/bin/lyc examples/fib.py -o fib_aot
          ./build/bin/lyc examples/fib_prim.py -o fib_prim_aot
          hyperfine -w 1 -r 5 "python3 examples/fib.py" "./build/bin/lyc jit examples/fib.py" "./fib_aot" "./fib_prim_aot"
