name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo curl -LsSf https://astral.sh/uv/install.sh | sh
          uv add flake8

      - name: Run Linter
        run: |
          source .venv/bin/activate
          flake8 . --ignore=E501 --exclude=.venv
